spring:
  application:
    name: multi-module-architecture
  sql:
    init:
      mode: always
# application properties
mma:
  outbound:
    advice-slip-api:
      url: "https://api.adviceslip.com"
  cache:
    enabled: false